version: 0.2
env:
  variables:
    BUCKET_NAME: "qqqwwwerrtyy123321"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - ISO_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)
      - TMP_DIR="dist-$ISO_DATE"
      - mkdir $TMP_DIR
      - cd $TMP_DIR
      - WAY_TO_DIR=$(pwd)
      - echo $WAY_TO_DIR
      - cd ..
      - cp *.py $WAY_TO_DIR
      - cp -rf env/lib/python3.6/site-packages/* $WAY_TO_DIR
      - cd $WAY_TO_DIR
      - PYTHON_FILE_NAME=$(ls grep | *.py)
      - LAMBDA_NAME="${PYTHON_FILE_NAME%.*}"
      - cd $WAY_TO_DIR; zip -r ../dist.zip *
      - cd ..
      - aws s3 cp dist.zip s3://$BUCKET_NAME/$LAMBDA_NAME/dist.zip
      - aws lambda update-function-code --function-name $LAMBDA_NAME --s3-bucket $BUCKET_NAME --s3-key $LAMBDA_NAME/dist.zip --publish
